seed: 42
cv_folds: 5

eligibility:
  base_models:
    lgbm: {n_estimators: 400, learning_rate: 0.05, num_leaves: 31}
    xgb:  {n_estimators: 400, learning_rate: 0.05, max_depth: 5}
    rf:   {n_estimators: 400, max_depth: 8, n_jobs: -1}
    logreg_l1: {C: 1.0}
  calibrate: isotonic
  metric_primary: auc_pr

aid:
  objective: multiclass
  lgbm: {n_estimators: 400, learning_rate: 0.05, num_leaves: 31}
